Profcess_Dev/urls.py
from django.contrib import admin
from django.urls import path, include
# from test_app import views
from accounts import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("findJob/", views.findJob, name="findJob"),
    path("careerAdvice/", views.careerAdvice, name="careerAdvice"),
    path("findATalent/", views.findATalent, name="findATalent"),
    path("services/", views.services, name="services"),
    path("contact/", views.contact, name="contact"),
    path("accounts/", include('accounts.urls')),
    path("recruiter/", include("recruiter_app.urls")),
    path("applicant/", include("applicant_app.urls")),
    path("college/",include("college_app.urls")),
    path("select2/", include("django_select2.urls")),
    path('', TemplateView.as_view(template_name="social_app/index.html")),  # added this
    path("accounts/", include('allauth.urls')),  # added this
    path("social/", include('social.urls', namespace='social')),
    path("accounts_social/", include('accounts_social.urls', namespace='accounts_social')),


path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view( template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view( template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),

     path('converter/',include('htmltopdf.urls'),name="converter"),
    # path("signup/", views.signup, name = "signup")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

college_app/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from college_app.views import Update_job,Delete_job
#from college_app.views import job_detail, Update_job,Delete_job,my_candidates,job_matching,search_candidates,campus_hiring,add_a_blog,assessments,recruiter_blog,applicant_detail


app_name = 'college'

urlpatterns = [
    path("create-college-user-profile/",
         views.createprofile, name="create_college_profile"),
    path("profile/",views.profile,name="profile"),
    path("create-job/", views.createjob, name="create_job"),
    path("posted-jobs/", views.posted_jobs, name="posted_jobs"),
    path("job-detail/<int:pk>", views.job_detail, name="job_detail"),
    path("job-detail/<int:pk>/update/", Update_job.as_view(), name = "update_job"),
    path("job-detail/<int:pk>/delete/", views.delete_job, name = "delete_job"),
    path("college-app/profile/",views.profile,name="profile"),
    #path("search-candidates/",views.search_candidates,name="search_candidates"),
    #path("my-candidate/", views.my_candidates, name="my_candidates"),
    #path("job-matching/<int:pk>", views.job_matching, name="job_matching"),
    #path("campus-hiring/", views.campus_hiring, name="campus_hiring"),
    #path("assessments/", views.assessments, name="assessments"),
    #path("add-a-blog/", views.add_a_blog, name="add_a_blog"),
    #path("recruiter-blog/", views.recruiter_blog, name="recruiter_blog"),
    #path("applicant-detail/<int:pk>", views.applicant_detail, name="applicant_detail"),
    #path("can/<int:pk>/<int:mk>/",views.can,name="can"),
    #path("alreadycan/<int:pk>/",views.alreadycan,name="alreadycan")



    # path('login/', auth_views.LoginView.as_view(),name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    # path('recruiter-signup/', views.RecruiterSignUp.as_view(), name="recruiter-signup"),
    # path('applicant-signup/', views.ApplicantSignUp.as_view(), name="applicant-signup"),
    # path('change-password/', auth_views.PasswordChangeView.as_view(template_name = "accounts/password_change_form.html", success_url = reverse_lazy("accounts:password_change_done")), name = "password_change"),
    # path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(template_name = "accounts/password_change_done.html"), name = "password_change_done"),


]

recruiter_app/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from recruiter_app.views import job_detail, Update_job,my_candidates,job_matching,search_candidates,campus_hiring,add_a_blog,assessments,recruiter_blog,applicant_detail
from django.views.static import serve
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
app_name = 'recruiter'



urlpatterns = [
    path("home/", views.home, name="home"), #<--changed this
    path("create-recruiter-user-profile/",
         views.createprofile, name="create_recruiter_profile"),
    path("<int:pk>/profile/",views.profile,name="profile"),
    path("create-job/", views.createjob, name="create_job"),
    path("posted-jobs/", views.posted_jobs, name="posted_jobs"),
    path("job-detail/<int:pk>", views.job_detail, name="job_detail"),
    path("job-detail/<int:pk>/update/", Update_job.as_view(), name = "update_job"),
    path("job-detail/<int:pk>/delete/", views.delete_job, name = "delete_job"),
    path("search-candidates/",views.search_candidates,name="search_candidates"),
# path("search-candidates/",views.search_candidates,name="search_candidates"),
   # path("search-candidates/",views.search_candidates1,name="search_candidates"),
    path("my-candidate/", views.my_candidates, name="my_candidates"),
    path("job-matching/<int:pk>", views.job_matching, name="job_matching"),
    path("campus-hiring/", views.campus_hiring, name="campus_hiring"),
    path("assessments/", views.assessments, name="assessments"),
    path("add-a-blog/", views.add_a_blog, name="add_a_blog"),
    path("recruiter-blog/", views.recruiter_blog, name="recruiter_blog"),
    path("applicant-detail/<int:pk>", views.applicant_detail, name="applicant_detail"),
    path("remove/<int:pk>",views.remove,name="remove"),
    path("view_applicants/<int:pk>",views.applicants,name="view_applicants"),
    path("can/<int:pk>",views.can,name="can"),
    path("can/<int:pk>/<int:mk>/",views.job_can,name="job_can"),
    path("alreadycan",views.alreadycan,name="alreadycan"),
    path("pricing/",views.pricing,name="pricing"),
    path("purchase-plan/",views.purchase_plan,name="purchase-plan"),
    path('<int:pk>/upload_pic/', views.upload_pic, name='upload_pic'),
    path("dashboard",views.dashboard,name='dashboard'),
    path('<int:pk>/delete_pic/', views.delete_pic, name='delete_pic'),
    path('cart_summary/',views.cart_summary,name='cart_summary'),
    path('payu_payment/',views.payu_payment,name='payment'),
     path('success/',views.success,name='success'),
    path('failure',views.failure,name='failure'),
    path('paypal_payment/',views.paypal_payment,name='paypal_payment'),
    path('plan/',views.plan,name='plan'),
    url(r'^download/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    #path('create-job/ajax/load-cities/', views.load_cities, name='ajax_load_cities'),






    # path('login/', auth_views.LoginView.as_view(),name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    # path('recruiter-signup/', views.RecruiterSignUp.as_view(), name="recruiter-signup"),
    # path('applicant-signup/', views.ApplicantSignUp.as_view(), name="applicant-signup"),
    # path('change-password/', auth_views.PasswordChangeView.as_view(template_name = "accounts/password_change_form.html", success_url = reverse_lazy("accounts:password_change_done")), name = "password_change"),
    # path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(template_name = "accounts/password_change_done.html"), name = "password_change_done"),


]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from django.urls.conf import include
from social import views

app_name = 'social'

urlpatterns = [
    path('home/', views.HomeView.as_view(), name="home"),
    path('about/', views.AboutView.as_view()),
    path('contact/', views.ContactView.as_view()),
    path('profile/edit/<int:pk>', views.MyProfileUpdateView.as_view(success_url="/social/home")),
    path('mypost/create/', views.MyPostCreate.as_view(success_url="/social/mypost")),
    path('mypost/delete/<int:pk>', views.MyPostDeleteView.as_view(success_url="/social/mypost")),
    path('mypost/', views.MyPostListView.as_view()),
    path('mypost/<int:pk>', views.MyPostDetailView.as_view()),

    path('myprofile/', views.MyProfileListView.as_view()),
    path('myprofile/<int:pk>', views.MyProfileDetailView.as_view()),

    path('myprofile/follow/<int:pk>', views.follow),
    path('myprofile/unfollow/<int:pk>', views.unfollow),

    path('mypost/like/<int:pk>', views.like),
    path('mypost/unlike/<int:pk>', views.unlike),
    #path('applicant/', include('applicant.urls', namespace='applicant')),
]

college_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import UserProfileForm,UserUpdateFormCollege,Jobs,JobUpdationForm,JobCreationForm
from .models import CollegeUserProfile, Jobs
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView, DeleteView
from django import forms
from accounts.models import ProfcessUser
from django.conf import settings
from django.core.mail import send_mail
from applicant_app.models import ApplicantUserProfile
from django.db.models import Q
from django.db.models import F
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect

# Create your views here.
# from ..recruiter_app.forms import UserUpdateForm



@login_required
def createprofile(request):
	if request.method == "POST":
		form = UserProfileForm(request.POST)
		if form.is_valid():
			userprofile = form.save(commit=False)
			userprofile.user = request.user
			userprofile.save()
			return render(request, "college_app/thanks.html")  # return page after filling userinfo form

		else:
			return "#########"

	else:
		form = UserProfileForm()
		return render(request, "college_app/userprofileform.html", {"form": form})

@login_required
def profile(request):
	if request.method == 'POST':
		c_form = UserUpdateFormCollege(request.POST, instance=request.user)

		if c_form.is_valid():
			c_form.save()
			return render(request, 'college_app/update_success.html')
	else:
		c_form = UserUpdateFormCollege(instance=request.user)
	context = {
		'c_form': c_form,

	}
	return render(request, 'college_app/profile.html', context)

@login_required
def createjob(request):
	if request.method == "POST":
		form = JobCreationForm(request.POST)
		if form.is_valid():
			job = form.save(commit=False)
			job.posted_by = request.user
			job.save()
			context = {
				"job": job,
			}
			context['job'] = job
			return render(request,"college_app/job_detail.html",context)  # return page after posting a new job
			pass
		else:
			pass
		pass
	else:
		form = JobCreationForm()
		return render(request, "college_app/createjob.html", {"form": form})
		pass



@login_required
def job_detail(request, pk=None):
    job = Jobs.objects.get(pk=pk)
    result = job.job_requirements
    mn = ApplicantUserProfile.objects.all()
    oo = ApplicantUserProfile.objects.none()
    z = []
    for mm in mn:
        jk = mm.skill_info
        for x in result:
            for y in jk:
                if x == y:
                    z.append(mm.user)
    for ui in z:
        i = ApplicantUserProfile.objects.filter(user=ui)
        oo |= i
    qs1 = job.applied_by.all()
    p = ApplicantUserProfile.objects.none()
    q = ApplicantUserProfile.objects.none()
    for k in qs1:
        qs2 = ApplicantUserProfile.objects.filter(user=k)
        p |= qs2
    q |= oo.exclude(pk__in=p)
    q |= q
    context = {
			'job': job,
			'qs': q,
			'count': len(q),
			'count1': len(p),
			'qs1': p,
		}
    context['job'] = job
    return render(request, "college_app/job_detail.html", context)

# def job_detail(request, pk=None):
# 	job = Job.objects.get(pk=pk)
# 	context={}
# 	context['job'] = job
# 	return render(request, "college_app/job_detail.html", context)

class Update_job(UpdateView):
	model=Jobs
	fields = ("primary_profile", "working_hour",
			  "notice_period", "essential_skills", "industry_type", "job_title", "job_info", 'job_vacancies',
			  "pincode", "exp_req", "cert_req", "types_of_job", "education_quali", "job_salary", "maximum",
			  "minimum", "other",
			  "city", "state", "start_date", "job_requirements", "cert", "lor", "wh", "others")
	widgets = {
		'job_title': forms.TextInput(attrs={'placeholder': 'UX/UI Designer'}),
		'city': forms.Select(attrs={'class': 'select-css'}),
		'notice_period': forms.Select(attrs={'class': 'select-css'}),
		'primary_profile': forms.Select(attrs={'class': 'select-css', }),
		'state': forms.Select(attrs={'class': 'select-css'}),
		'working_hour': forms.Select(attrs={'class': 'select-css'}),
		'industry_type': forms.Select(attrs={'class': 'select-css'}),
		'pincode': forms.TextInput(attrs={'placeholder': '123456'}),
		'job_vacancies': forms.Select(attrs={'class': 'select-css'}),
		'minimum': forms.TextInput(attrs={'placeholder': '   20,000            INR'}),
		'maximum': forms.TextInput(attrs={'placeholder': '   40,000            INR'}),
		'types_of_job': forms.Select(attrs={'class': 'select-css'}),
		'cert_req': forms.TextInput(attrs={'placeholder': 'e.g.ABC'}),
		'exp_req': forms.Select(attrs={'class': 'select-css'}),
	}
	template_name = 'college_app/createjob.html'


	def form_valid(self, form):
		form.instance.posted_by = self.request.user
		return super().form_valid(form)


def delete_job(request, pk):
	context = {}
	obj = get_object_or_404(Jobs, id=pk)
	if request.method == "POST":
		# delete object
		obj.delete()
		# after deleting redirect to
		# home page
		return HttpResponseRedirect("/college/posted-jobs/")

	return render(request, "college_app/posted_jobs.html", context)


k = ""
prof = ""

class Delete_job(DeleteView):
	model = Jobs
	success_url = '/'

@login_required
def posted_jobs(request):
	"""
	View to fetch and display the list of jobs posted by a college.
	"""

	jobs = request.user.college_jobs.all()
	context = {
		"jobs": jobs,
	}
	return render(request, "college_app/posted_jobs.html", context)

college_app/templates/college_app/job_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <!-- Masthead-->
<header class="masthead auth">
  <div class="container">
  <div class="row">
    <div class="col-md-4 col-xs-8 formDesign">
    <h1>DELETE JOB ?</h1>
      <form method="POST" class="form">
        {% csrf_token %}
        {{form.as_p}}
        <h2>Are you sure you want to delete the {{job.job_title}}?</h2>
        <button type="submit" class="btn btn-outline-danger">DELETE</button>
        <a href="{% url 'recruiter:job_detail' pk=job.pk  %}" class="btn btn-secondary" >CANCEL</a>
      </form>
    </div>
    <div class="col-md-4 col-xs-2"></div>
  </div>
    
  </div>
</header>
{% endblock content %}

college_app/templates/college_app/posted_jobs.html
{% extends "dashboard.html" %} {% block content %}
<br><br>

<!-- <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script> -->
<style>
    td{padding:20px; }
    .card-body {
                margin:10px, 10px;
                padding:4px;
                width: max-width ;
                height: auto;
                text-align:justify;

            }
    .right {
  margin-right:0px;
  margin-left: 400px;
}
.modal-confirm {
	color: #636363;
	width: 400px;
	position: absolute;
    left: 40%;
    top: 40%;


}
.modal-confirm .modal-content {
	padding: 10px;
	border-radius: 5px;
	border: none;
	text-align: center;
	font-size: 0px;
	border-radius: 25px;
}
.modal-confirm .modal-header {
	border-bottom: none;
	position: relative;

}
.modal-confirm h5 {
	text-align: center;
	font-size: 26px;
	margin: 30px 0 -10px;
}

.modal-confirm .modal-body {
	color: #999;
}
.modal-confirm .modal-footer {
	border: none;
	text-align: center;
	border-radius: 5px;
	font-size: 13px;
	padding: 10px 15px 25px;
}
.modal-confirm .modal-footer a {
	color: #999;
}

.modal-confirm .btn, .modal-confirm .btn:active {
	color: #000;
	border-radius: 4px;
	background: #ffffff;
	text-decoration: none;
	transition: all 0.4s;
	line-height: normal;
	min-width: 120px;
	border: none;
	min-height: 40px;
	margin: 0 5px;
}
.modal-confirm .btn-secondary {
	background: #ffffff;
	border-radius: 15px;
	height:40px;
	width: 20px;
	text-align: center;
	line-height: 20px;
	border: 0.5px solid black;
	font-weight: bold;
	margin : 20px;
}
.modal-confirm .btn-secondary:hover, .modal-confirm .btn-secondary:focus {
	background: #a8a8a8;
}
.modal-confirm .btn-danger {
	background: #f15e5e;
	color: #fff;
	border-radius: 15px;
	height:40px;
	width: 40px;
	text-align: center;
	line-height: 20px;
	border: 0.5px solid black;
	font-weight: bold;
	margin : 20px;
}
.modal-confirm .btn-danger:hover, .modal-confirm .btn-danger:focus {
	background: #ee3535;
}
</style>
<div >
  <center><h1 style="color: #246ebd; padding=5px; font-size:40px">MY JOB LISTING</h1></center>
</div>
    <div>
        <div>
            <div>
                <div >

                    <div class="card-body">
                        <div class="scroll">
                      <!--  <div class="alert alert-primary" role="alert">
                            You have posted {{ count }} jobs!
                        </div> -->
                        {% if jobs %}
                            <div >
                                <br>
                                {% for job in jobs %}
                                <div style="width: 92%;
  margin-left:80px;border-style: solid; border-color: rgba(0, 0, 0, 0.699); border-width: 2px; border-radius: 20px;">
                                    <table style="width:100%">
                                        <tr>
                                        <td style="width:9%;">
                                            <i class='fas fa-city' style="font-size:48px;color:white; border-style: double; background-color: #003399; padding:30px; border-radius: 150px;"></i>
                                        </td>
                                    <div>
                                        <td style="width:20%; text-align:left;">
                                            <p style="font-size: 30px; font-color: rgba(54, 55, 56, 0.637); font-weight: 700;"><strong><a href="{% url 'recruiter:job_detail' pk=job.pk  %}">{{ job.job_title }}</a></strong></p>
                                            <p style="font-size: 25px; font-color: rgba(54, 55, 56);font-weight: 400;"><a href="{% url 'recruiter:job_detail' pk=job.pk  %}">{{ user.company_name }}</a></p>
                                        <p style="font-weight:bold;">{{ job.types_of_job }}</p>
                                        </td>
                                    </div>
                                    <div>
                                        <td style="text-align:left;width:20%">
                                            <br>
                                      <p style="font-size:13px; font-weight:bold;'">{{ job.minimum }} - {{ job.maximum }}LPA</p>
                                        <p style="font-size:13px; font-weight:bold;">Experience - {{ job.exp_req }}</p>
                                        <p style="font-size:13px; font-weight:bold;">Duration - {{ job.job_duration }}</p>
                                      </td>
                                    </div>
                                    <div>
                                        <td style="width:20%">
                                            <br><br>
                                        <p style="font-size:13px; font-weight:bold;color:red; text-align:center;">Apply By - {{ job.start_date }}</p>
                                        <p style="font-size:13px; font-weight:bold;text-align:center;">Location - {{ job.city }},{{ job.state }}</p>
                                        </td>
                                    </div>
                                    <div class="right">
                                    <td align="right">
                                    <table style="width:100px;">
                                    <tr><td><a class="btn btn-primary" style="border-radius: 30px;height:50px; width: 150px; text-align: center; line-height: 30px;" href=#>View Applicant</a></td>
                                     <td><a class="btn btn-primary" style="border-radius: 30px;height:50px; width: 150px; text-align: center; line-height: 30px;" href="{% url 'college:update_job' pk=job.pk %}">Edit Job</a> </td>
                                      </tr>
                                       <tr>
                                        <td><a class="btn btn-warning" style="border-radius: 30px;height:50px; width: 150px; text-align: center; line-height: 30px;" href="{% url 'college:job_detail' pk=job.pk %}">Description</a></td>
                                           <td><button type ="button" data-target="#myModal{{ job.pk }}" data-toggle="modal" class="btn btn-warning" style=" border-radius: 30px; height:50px; width: 150px; text-align: center; line-height: 30px;">Remove</button></td>
                                     </tr>
                                     </table>
                                    </td></div>
                                    </tr>

                                    </table>
                                </div>
                                <br>

                            </div><!-- Modal HTML -->
                         {% endfor %} {% else %}
                            <p>You haven't posted any jobs</p>
                        {% endif %}
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
<br><br>
{% for job in jobs %}
<div id="myModal{{ job.pk }}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModal" aria-hidden="true">
	<div class="modal-dialog modal-confirm">
		<div class="modal-content">
			<div class="modal-header flex-column">
                <h4 class="modal-title w-100"><b>Do You Want To Delete This Job?</b></h4>
               </div><br><br>
			<div class="modal-footer justify-content-center">
                <form method="POST" action="{% url 'college:delete_job' pk=job.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-secondary">Yes</button>
				<button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                </form>
			</div>
		</div>
	</div>
</div>
{% endfor %}
{% endblock content %}

college_app/templates/college_app/profile.html
{% extends "dashboard.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<br><br><br><br><br><br><br>

    <div class="container-fluid mt--6">
        <div class="row justify-content-center">
            <div class="col-md-8 col-12">
                <div class="card">
                    <div class="row justify-content-center">
                        <div class="col-lg-3 order-lg-2">
                            <div class="card-profile-image">
                                <a href="#">
                                    <img src="{% static 'dashboard/img/theme/person.png' %}" class="rounded-circle"
                                         alt="profile">
                                    <img src="{{ url }}" alt="">
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
                        <div class="d-flex justify-content-between">
                        </div>
                    </div>
                    <div class="card-body container col-md-10">
                        <div class="row">
                            <div class="col">
                                <div class="card-profile-stats d-flex justify-content-center">
                                    <div>
                                        <h1>{{ user.username }}</h1>
                                        <div class="h5 font-weight-300">
                                            <i class="ni location_pin mr-2"></i>{{ user.email }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="">
                                <h1>Edit Profile</h1>
                            </div>
                        </div>
                        <div class="row">
                            <form method="POST" class="form" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    {% for i in c_form %}
                                        <div class="col-6">
                                            <label for="id_{{ i.name }}">{{ i.label }}:</label>
                                            <input class="form-control" type="text" name="{{ i.name }}"
                                                   id="id_{{ i.name }}" value="{{ i.value }}">
                                        </div>
                                    {% endfor %}
                                </div>
                                <div class="row justify-content-center">
                                    <div class="text-center m-2">
                                        <button type="submit" class="btn btn-primary">Save</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

college_app/templates/college_app/thanks.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
      <h1>Thanks for filling up the profile.</h1>
  </div>
{% endblock content %}

college_app/templates/college_app/update_success.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
      <br><br><br><br><br>
      <h1>Profile Updated!!</h1>
  </div>
{% endblock content %}

college_app/templates/college_app/userprofileform.html
{% extends "dashboard.html" %}

{% block content %}
    <div class="container-fluid mt--6">
        <div class="row justify-content-center">
            <div class="col-md-8 col-12">
                <div class="card">
                    <!-- Card header -->
                    <div class="card-header">
                        <h1 class="mb-0">User Profile Form</h1>
                    </div>
                    <!-- Card body -->
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group row justify-content-center">
                                    <label for="example-text-input" class="col-md-3 col-4 col-form-label form-control-label">{{ field.label_tag }}</label>
                                    <div class="col-md-9 col-8">
                                        {{ field }}
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}