Profcess_Dev/urls.py
from django.contrib import admin
from django.urls import path, include
# from test_app import views
from accounts import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("findJob/", views.findJob, name="findJob"),
    path("careerAdvice/", views.careerAdvice, name="careerAdvice"),
    path("findATalent/", views.findATalent, name="findATalent"),
    path("services/", views.services, name="services"),
    path("contact/", views.contact, name="contact"),
    path("accounts/", include('accounts.urls')),
    path("recruiter/", include("recruiter_app.urls")),
    path("applicant/", include("applicant_app.urls")),
    path("college/",include("college_app.urls")),
    path("select2/", include("django_select2.urls")),
    path('', TemplateView.as_view(template_name="social_app/index.html")),  # added this
    path("accounts/", include('allauth.urls')),  # added this
    path("social/", include('social.urls', namespace='social')),
    path("accounts_social/", include('accounts_social.urls', namespace='accounts_social')),


path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view( template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view( template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),

     path('converter/',include('htmltopdf.urls'),name="converter"),
    # path("signup/", views.signup, name = "signup")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from accounts.views import password_reset_request

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUp1, name="signup"),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('index/',views.index,name="index"),
    path('recruiter-signup/', views.recruiter_signup, name="recruiter-signup"),
    path('activate/<uid>/<token>/', views.activate, name='activate'),
    path('applicant-signup/', views.ApplicantSignUp, name="applicant-signup"),
    path('college-signup/', views.college_signup, name="college-signup"),
    path('email_form/',views.email_form,name="email_form"),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name="accounts/password_change_form.html",
                                                                   success_url=reverse_lazy(
                                                                       "accounts:password_change_done")),
         name="password_change"),
    path('change-password/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"),
         name="password_change_done"),
    path('applicant-signup/privacy.html', views.showprivacy, name="showprivacy"),
    path('applicant-signup/terms.html', views.showterms, name="showterms"),
    path('recruiter-signup/privacy.html', views.showprivacy, name="showprivacy"),
    path('recruiter-signup/terms.html', views.showterms, name="showterms"),
    path('college-signup/privacy.html', views.showprivacy, name="showprivacy"),
    path('college-signup/terms.html', views.showterms, name="showterms"),
    path('about/', views.about, name="about"),
    path('upload-csv/', views.profile_upload, name="profile_upload"),
path("password_reset/", views.password_reset_request, name="password_reset")

]

applicant_app/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views


app_name = 'applicant'

urlpatterns = [
    path("create-applicant-user-profile/", views.createprofile, name = "create_applicant_profile"),
    path("jobs-list", views.search_job, name= "jobs_list"),
    path("job-detail/<int:pk>", views.job_detail, name = "job_detail"),
    path("applytojob/<int:pk>", views.applytojob, name = "applytojob"),
    path('activate/<uid>/<token>/', views.activate, name='activate'),
    path("job_search", views.search_job, name = "job_search"),
    path("job_alert", views.job_alert, name = "job_alert"),
    path("job_recommendations", views.job_recommendations, name = "job_recommendations"),
    path("job_companies", views.job_companies, name = "job_companies"),
    path("career_guidance", views.career_guidance, name = "career_guidance"),
    path("interview_tips", views.interview_tips, name = "interview_tips"),
    path("expert_call", views.expert_call, name = "expert_call"),
    path("matching_job", views.matching_job, name = "matching_job"),
    path("<int:pk>/view_profile/",views.view_profile,name="view_profile"),
    path('<int:pk>/edit_profile/', views.edit_profile, name='edit_profile'),
    path('<int:pk>/upload_pic/', views.upload_pic, name='upload_pic'),
    path('<int:pk>/upload_resume/', views.upload_resume, name='upload_resume'),
    path("job_searchfreshers", views.job_searchfreshers, name = "job_searchfreshers"),
    path("job_searchwfh", views.job_searchwfh, name = "job_searchwfh"),
    path("shortlist",views.shortlist_job,name="shortlist_job"),
    path("my_jobs",views.my_jobs,name="my_jobs"),
    path("withdraw_job/<int:pk>",views.withdraw_job,name="withdraw_job"),
    path("withdraw_job/my_jobs",views.my_jobs,name="my_jobs"),
    path("job_detail",views.job_detail,name="job_detail"),
    #path("search", views.search, name = "search"),
    # path('login/', auth_views.LoginView.as_view(),name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    # path('recruiter-signup/', views.RecruiterSignUp.as_view(), name="recruiter-signup"),
    # path('applicant-signup/', views.ApplicantSignUp.as_view(), name="applicant-signup"),
    # path('change-password/', auth_views.PasswordChangeView.as_view(template_name = "accounts/password_change_form.html", success_url = reverse_lazy("accounts:password_change_done")), name = "password_change"),
    # path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(template_name = "accounts/password_change_done.html"), name = "password_change_done"),


]

recruiter_app/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from recruiter_app.views import job_detail, Update_job,my_candidates,job_matching,search_candidates,campus_hiring,add_a_blog,assessments,recruiter_blog,applicant_detail
from django.views.static import serve
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
app_name = 'recruiter'



urlpatterns = [
    path("home/", views.home, name="home"), #<--changed this
    path("create-recruiter-user-profile/",
         views.createprofile, name="create_recruiter_profile"),
    path("<int:pk>/profile/",views.profile,name="profile"),
    path("create-job/", views.createjob, name="create_job"),
    path("posted-jobs/", views.posted_jobs, name="posted_jobs"),
    path("job-detail/<int:pk>", views.job_detail, name="job_detail"),
    path("job-detail/<int:pk>/update/", Update_job.as_view(), name = "update_job"),
    path("job-detail/<int:pk>/delete/", views.delete_job, name = "delete_job"),
    path("search-candidates/",views.search_candidates,name="search_candidates"),
# path("search-candidates/",views.search_candidates,name="search_candidates"),
   # path("search-candidates/",views.search_candidates1,name="search_candidates"),
    path("my-candidate/", views.my_candidates, name="my_candidates"),
    path("job-matching/<int:pk>", views.job_matching, name="job_matching"),
    path("campus-hiring/", views.campus_hiring, name="campus_hiring"),
    path("assessments/", views.assessments, name="assessments"),
    path("add-a-blog/", views.add_a_blog, name="add_a_blog"),
    path("recruiter-blog/", views.recruiter_blog, name="recruiter_blog"),
    path("applicant-detail/<int:pk>", views.applicant_detail, name="applicant_detail"),
    path("remove/<int:pk>",views.remove,name="remove"),
    path("view_applicants/<int:pk>",views.applicants,name="view_applicants"),
    path("can/<int:pk>",views.can,name="can"),
    path("can/<int:pk>/<int:mk>/",views.job_can,name="job_can"),
    path("alreadycan",views.alreadycan,name="alreadycan"),
    path("pricing/",views.pricing,name="pricing"),
    path("purchase-plan/",views.purchase_plan,name="purchase-plan"),
    path('<int:pk>/upload_pic/', views.upload_pic, name='upload_pic'),
    path("dashboard",views.dashboard,name='dashboard'),
    path('<int:pk>/delete_pic/', views.delete_pic, name='delete_pic'),
    path('cart_summary/',views.cart_summary,name='cart_summary'),
    path('payu_payment/',views.payu_payment,name='payment'),
     path('success/',views.success,name='success'),
    path('failure',views.failure,name='failure'),
    path('paypal_payment/',views.paypal_payment,name='paypal_payment'),
    path('plan/',views.plan,name='plan'),
    url(r'^download/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    #path('create-job/ajax/load-cities/', views.load_cities, name='ajax_load_cities'),






    # path('login/', auth_views.LoginView.as_view(),name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    # path('recruiter-signup/', views.RecruiterSignUp.as_view(), name="recruiter-signup"),
    # path('applicant-signup/', views.ApplicantSignUp.as_view(), name="applicant-signup"),
    # path('change-password/', auth_views.PasswordChangeView.as_view(template_name = "accounts/password_change_form.html", success_url = reverse_lazy("accounts:password_change_done")), name = "password_change"),
    # path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(template_name = "accounts/password_change_done.html"), name = "password_change_done"),


]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from django.urls.conf import include
from social import views

app_name = 'social'

urlpatterns = [
    path('home/', views.HomeView.as_view(), name="home"),
    path('about/', views.AboutView.as_view()),
    path('contact/', views.ContactView.as_view()),
    path('profile/edit/<int:pk>', views.MyProfileUpdateView.as_view(success_url="/social/home")),
    path('mypost/create/', views.MyPostCreate.as_view(success_url="/social/mypost")),
    path('mypost/delete/<int:pk>', views.MyPostDeleteView.as_view(success_url="/social/mypost")),
    path('mypost/', views.MyPostListView.as_view()),
    path('mypost/<int:pk>', views.MyPostDetailView.as_view()),

    path('myprofile/', views.MyProfileListView.as_view()),
    path('myprofile/<int:pk>', views.MyProfileDetailView.as_view()),

    path('myprofile/follow/<int:pk>', views.follow),
    path('myprofile/unfollow/<int:pk>', views.unfollow),

    path('mypost/like/<int:pk>', views.like),
    path('mypost/unlike/<int:pk>', views.unlike),
    #path('applicant/', include('applicant.urls', namespace='applicant')),
]

applicant_app/forms.py
from django import forms
from multiselectfield import MultiSelectFormField
from .models import ApplicantUserProfile

year=[tuple([x,x]) for x in range(1980,2020)]
class UserProfileForm(forms.ModelForm):
    # preferred_domain = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    skill_info = forms.MultipleChoiceField(choices=ApplicantUserProfile.SKILLS,required=False)
    class Meta:
        model = ApplicantUserProfile
        fields = ("headline","first_name","last_name","pheadline","current_position","education","country_region","location",
        "industry","contact_information","description","school_name","school_degree","field_of_study","location_of_school",
        "start_school","end_school","experience_title","company_name","company_city","company_state","start_company",
        "end_company", "area_of_expertise",
        "project_name","start_project","end_project","project_creator","associated_with",
        "project_url","project_description",
        "accomplishment_title","accomplishment_associated_with","issuer","issue_date","accomplishment_description","skill_info","profile_pic","gender","dob","mailid")
    pass

class UserProfileUpdationForm(forms.ModelForm):
    skill_info = forms.MultipleChoiceField(choices=ApplicantUserProfile.SKILLS,required=False)
    class Meta:
        model = ApplicantUserProfile
        fields = ("headline","first_name","last_name","pheadline","current_position","education","country_region","location",
        "industry","contact_information","description","school_name","school_degree","field_of_study","location_of_school",
        "start_school","end_school","experience_title","company_name","company_city","company_state","start_company",
        "end_company", "area_of_expertise",
        "project_name","start_project","end_project","project_creator","associated_with",
        "project_url","project_description",
        "accomplishment_title","accomplishment_associated_with","issuer","issue_date","accomplishment_description","skill_info","profile_pic","gender","dob","mailid")
    pass

class PicForm(forms.ModelForm):

    class Meta:
        model = ApplicantUserProfile
        fields = ("profile_pic",)
    pass

class ResumeForm(forms.ModelForm):

    class Meta:
        model = ApplicantUserProfile
        fields = ("profile_resume",)
    pass

class InputForm(forms.Form):

    fullname = forms.CharField(max_length = 200)
    mail = forms.EmailField()
    contact = forms.IntegerField()

applicant_app/templates/applicant_app/activation.html
{% extends "base.html" %}


{% block content %}

<h1>Activation Successful!</h1>
    <div class='alert alert-info'></div>
    <h1>Activation Successful!</h1>
        <a href="{% url 'applicant:jobs_list' %}">Click to Continue</a>
    </div>
{% endblock content%}

applicant_app/templates/applicant_app/applicationdonealready.html
{% extends "dashboard.html" %}
{% block content %}
  <div class="container">
      <h1>Application to {{ job.job_title }} done already by {{ user.username }}
</h1>
  </div>
{% endblock content %}

applicant_app/templates/applicant_app/applytojob.html
{% extends "dashboard.html" %}
{% block content %}
  <div class="container">
      <h1>Successfully Applied to Job</h1>
  </div>
{% endblock content %}
Successfully Applied to Job

applicant_app/templates/applicant_app/career_guidance.html
{% extends "dashboard.html" %}
{% block content %}
<h1>
    guidance
</h1>
{% endblock content %}

applicant_app/templates/applicant_app/expert_call.html
{% extends "dashboard.html" %}
{% block content %}
<h1>
    expert call
</h1>
{% endblock content %}

applicant_app/templates/applicant_app/fill_application.html
{% extends "dashboard.html" %}
{% block content %}
<h1>
    Kindly complete your profile here
    <br>
    <a href="{% url 'applicant:create_applicant_profile'  %}"><button class="btn btn-primary"><b>Complete Profile -></b></button></a>
</h1>
{% endblock content %}

applicant_app/templates/applicant_app/job_alert.html
{% extends "dashboard.html" %}
{% block content %}
<h1>
    job alert
</h1>
{% endblock content %}

applicant_app/templates/applicant_app/matching_job.html
{% extends "dashboard.html" %}
{% block content %}
<h1>
    Matching job
</h1>
 {% if jobs %}
<div class="card-body bg-transparent border-0">
                         <ul class="list-group list-group-flush">
                                {%for job in jobs %}
                                  <div style="box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                                  transition: 0.3s;
                                  width: 100%;
                                  border-radius: 5px;">
                                    <a href="{% url 'applicant:job_detail' pk=job.pk %}">
                                        <li class="list-group-item">{{ job.job_title }}</li>
                                    </a>
                                    <div class="media-body">
                                                    <span class="pl-2 text-sm">Job Salary: {{ job.job_salary }}</span><br>
                                                    <span class="pl-2 text-sm">Company name: {{job.company_name}}</span><br>
                                                    <span class="pl-2 text-sm">Type of Job :{{job.type_of_job}}</span><br>
                                                    <span class="pl-2 text-sm">job Location :{{job.job_location}}</span><br>
                                                    <span class="pl-2 text-sm">job Requirements: {{job.job_requirements}}</span>

                                    </div>
                                      <div style="margin-left:60%">
                                      <a href="{% url 'applicant:applytojob' pk=job.pk %}">
                                          <button type="button" style="left-margin:20px" class="btn btn-primary mb-3">Apply Now</button>
                                      </a>

                                      <a  href="{% url 'applicant:shortlist_job' %}">
                                          <button type="button" style="background-color:#FF7F50" class="btn btn-primary mb-3">Save</button>
                                      </a>
                                      </div>


                                  </div>
                             <br>

                            </ul>

                                {% endfor %}
                        {% else %}
                        <div class="card-header bg-transparent border-0">
                        <span> NO result found</span>
                    </div>
    {% endif %}
                    </div>
                </div>
            </div>


{% endblock content %}

applicant_app/templates/applicant_app/my_jobs.html
{% extends "dashboard.html" %} {% block content %}
<br><br>

<!-- <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script> -->
<style>
    td{padding:20px; }
    .card-body {
                margin:10px, 10px;
                padding:4px;
                width: max-width ;
                height: auto;
                text-align:justify;

            }
    .right {
  margin-right:0px;
  margin-left: 400px;
}
.modal-confirm {
	color: #636363;
	width: 400px;
	position: absolute;
    left: 40%;
    top: 40%;


}
.modal-confirm .modal-content {
	padding: 10px;
	border-radius: 5px;
	border: none;
	text-align: center;
	font-size: 0px;
	border-radius: 25px;
}
.modal-confirm .modal-header {
	border-bottom: none;
	position: relative;

}
.modal-confirm h5 {
	text-align: center;
	font-size: 26px;
	margin: 30px 0 -10px;
}

.modal-confirm .modal-body {
	color: #999;
}
.modal-confirm .modal-footer {
	border: none;
	text-align: center;
	border-radius: 5px;
	font-size: 13px;
	padding: 10px 15px 25px;
}
.modal-confirm .modal-footer a {
	color: #999;
}

.modal-confirm .btn, .modal-confirm .btn:active {
	color: #000;
	border-radius: 4px;
	background: #ffffff;
	text-decoration: none;
	transition: all 0.4s;
	line-height: normal;
	min-width: 120px;
	border: none;
	min-height: 40px;
	margin: 0 5px;
}
.modal-confirm .btn-secondary {
	background: #ffffff;
	border-radius: 15px;
	height:40px;
	width: 20px;
	text-align: center;
	line-height: 20px;
	border: 0.5px solid black;
	font-weight: bold;
	margin : 20px;
}
.modal-confirm .btn-secondary:hover, .modal-confirm .btn-secondary:focus {
	background: #a8a8a8;
}
.modal-confirm .btn-danger {
	background: #f15e5e;
	color: #fff;
	border-radius: 15px;
	height:40px;
	width: 40px;
	text-align: center;
	line-height: 20px;
	border: 0.5px solid black;
	font-weight: bold;
	margin : 20px;
}
.modal-confirm .btn-danger:hover, .modal-confirm .btn-danger:focus {
	background: #ee3535;
}
</style>
<div >
  <center><h1 style="color: #246ebd; padding=5px; font-size:40px">MY JOB LISTING</h1></center>
</div>
    <div>
        <div>
            <div>
                <div >

                    <div class="card-body">
                        <div class="scroll">
                      <!--  <div class="alert alert-primary" role="alert">
                            You have posted {{ count }} jobs!
                        </div> -->
                        {% if jobs %}
                            <div >
                                <br>
                                {% for job in jobs %}
                                <div style="width: 92%;
  margin-left:80px;border-style: solid; border-color: rgba(0, 0, 0, 0.699); border-width: 2px; border-radius: 20px;">
                                    <table style="width:100%">
                                        <tr>
                                        <td style="width:9%;">
                                            <i class='fas fa-city' style="font-size:48px;color:white; border-style: double; background-color: #003399; padding:30px; border-radius: 150px;"></i>
                                        </td>
                                    <div>
                                        <td style="width:20%; text-align:left;">
                                            <p style="font-size: 30px; font-color: rgba(54, 55, 56, 0.637); font-weight: 700;"><strong><a href="{% url 'recruiter:job_detail' pk=job.pk  %}">{{ job.job_title }}</a></strong></p>
                                            <p style="font-size: 25px; font-color: rgba(54, 55, 56);font-weight: 400;"><a href="{% url 'recruiter:job_detail' pk=job.pk  %}">{{ user.company_name }}</a></p>
                                        <p style="font-weight:bold;">{{ job.types_of_job }}</p>
                                        </td>
                                    </div>
                                    <div>
                                        <td style="text-align:left;width:20%">
                                            <br>
                                      <p style="font-size:13px; font-weight:bold;'">{{ job.job_salary }} LPA</p>
                                        <p style="font-size:13px; font-weight:bold;">Experience - {{ job.exp_req }}</p>
                                        <p style="font-size:13px; font-weight:bold;">Duration - {{ job.job_duration }}</p>
                                      </td>
                                    </div>
                                    <div>
                                        <td style="width:20%">
                                            <br><br>
                                        <p style="font-size:13px; font-weight:bold;color:red; text-align:center;">Apply By - {{ job.start_date }}</p>
                                        <p style="font-size:13px; font-weight:bold;text-align:center;">Location - {{ job.city }},{{job.state}}</p>
                                        </td>
                                    </div>
                                    <div class="right">
                                    <td align="right">
                                    <table style="width:100px;">

                                       <tr>
                                        <td><a class="btn btn-warning" style="border-radius: 30px;height:50px; width: 150px; text-align: center; line-height: 30px;" href="{% url 'applicant:job_detail' pk=job.pk %}">Description</a></td>
                                           <td><button type ="button" data-target="#myModal{{ job.pk }}" data-toggle="modal" class="btn btn-warning" style=" border-radius: 30px; height:100px; width: 150px; text-align: center; line-height: 30px;">Withdraw my application</button></td>
                                     </tr>
                                     </table>
                                    </td></div>
                                    </tr>

                                    </table>
                                </div>
                                <br>

                            </div><!-- Modal HTML -->
                         {% endfor %} {% else %}
                            <p>You haven't applied in any jobs</p>
                        {% endif %}
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
<br><br>
{% for job in jobs %}
<div id="myModal{{ job.pk }}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModal" aria-hidden="true">
	<div class="modal-dialog modal-confirm">
		<div class="modal-content">
			<div class="modal-header flex-column">
                <h4 class="modal-title w-100"><b>Do You Want To withdraw your application for This Job?</b></h4>
               </div><br><br>
			<div class="modal-footer justify-content-center">
                <form method="POST" action="{% url 'applicant:withdraw_job' pk=job.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-secondary">Yes</button>
				<button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                </form>
			</div>
		</div>
	</div>
</div>
{% endfor %}
{% endblock content %}

applicant_app/templates/applicant_app/search.html
{% extends "dashboard.html" %}

{% block content %}
    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row py-4">
                    <div class="col-lg-12">
                        <h6 class="h2 text-white mb-3">Job Listing</h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4 col-md-12">
                            <form  action="{% url 'applicant:search' %}" method="get" accept-charset="utf-8">
                                <div class="row align-items-center justify-content-center">
                                    <div class="col-md-1">
                                        <button class="btn bg-light searchbutton" type="submit">
                                          <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                    <div class="col-md-2">
                                        <input  id="query_title" name="query_title" type="text" placeholder="Search Job Title">
                                <!-- <button class="searchbutton" type="submit">
                                    <i class="fa fa-search"></i>
                                  </button> -->
                                  </div>
                                    <div class="col-md-2">
                                        <input  id="query_skills" name="query_skills" type="text" placeholder="Search by Skills">
                                    </div>
                                    <div class="col-md-2">
                                        <input  id="query_location" name="query_location" type="text" placeholder="Search by Location">
                                    </div>
                                </div>
                            </form>                 
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark mt-3">
                                <li class="breadcrumb-item"><a href="{% url 'applicant:jobs_list' %}"><i class="fas fa-home"></i></a></li>
                                <li class="breadcrumb-item active" aria-current="page">jobsList</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid mt--6">
        <div class="row justify-content-center">
            <div class="col-md-8 col-12">
                <div class="card">
                    <!-- Card header -->
                    <div class="card-header bg-transparent border-0">
                        <h1>Search Results</h1>
                    </div>
                    <!-- Translucent table -->
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col" class="sort" data-sort="name">JOB TITLE</th>
                            </tr>
                            </thead>
                            <tbody class="list">
                            {% if jobs|length < 1 %}
                            <p>
                                No search result found.

                                <!-- Your Search - <b>{{query_title}} </b>- did not match any Job.<br> -->

                                Suggestions:
                                <ul>
                                <li>
                                Try different keywords.
                                </li>
                                </ul>
                            </p>
                            {% endif %}
                            {% for job in jobs %}
                                <tr>
                                    <th scope="row">
                                        <a href="{% url 'applicant:job_detail' pk=job.pk %}">
                                            <div class="media align-items-center">
                                                <div class="media-body">
                                                    <span class="name mb-0 text-sm">{{ job.job_title }}</span><br>
                                                    <span class="pl-2 text-sm">Job Salary: {{ job.job_salary }}</span><br>
                                                    <span class="pl-2 text-sm">Company name: {{job.company_name}}</span><br>
                                                    <span class="pl-2 text-sm">Type of Job :{{job.type_of_job}}</span><br>
                                                    <span class="pl-2 text-sm">job Location :{{job.job_location}}</span><br>
                                                    <span class="pl-2 text-sm">job Requirements: {{job.job_requirements}}</span>

                                                </div>
                                            </div>
                                        </a>
                                    </th>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

applicant_app/templates/applicant_app/verifyemailfirst.html
{% extends "dashboard.html" %}
{% block content %}
  <div class="container">
      <h1>You have not verified your email yet. Kindly verify your email to apply for the job.
      <br> If you cannot find your confirmation email anymore, send yourself a new one here.
          <span><a href="{% url 'accounts:email_form' %}"><br>E-mail</a></span></h1>
  </div>
{% endblock content %}