Profcess_Dev/urls.py
from django.contrib import admin
from django.urls import path, include
# from test_app import views
from accounts import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("findJob/", views.findJob, name="findJob"),
    path("careerAdvice/", views.careerAdvice, name="careerAdvice"),
    path("findATalent/", views.findATalent, name="findATalent"),
    path("services/", views.services, name="services"),
    path("contact/", views.contact, name="contact"),
    path("accounts/", include('accounts.urls')),
    path("recruiter/", include("recruiter_app.urls")),
    path("applicant/", include("applicant_app.urls")),
    path("college/",include("college_app.urls")),
    path("select2/", include("django_select2.urls")),
    path('', TemplateView.as_view(template_name="social_app/index.html")),  # added this
    path("accounts/", include('allauth.urls')),  # added this
    path("social/", include('social.urls', namespace='social')),
    path("accounts_social/", include('accounts_social.urls', namespace='accounts_social')),


path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view( template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view( template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),

     path('converter/',include('htmltopdf.urls'),name="converter"),
    # path("signup/", views.signup, name = "signup")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

htmltopdf/urls.py
from django.urls import path
from htmltopdf import views

app_name='converter'

urlpatterns = [
    path('manual_resume',views.manual_resume.as_view(),name='manual'),
	path('template_sel/<int:from_index>/',views.template.as_view(),name='select'),
	path('<int:temp_index>/', views.fork.as_view(),name='fork'),
    path('pdf_view/', views.ViewPDF.as_view(), name="pdf_view"),
    path('pdf_download/', views.DownloadPDF.as_view(), name="pdf_download"),
]

social/urls.py
from django.urls import path
from django.urls.conf import include
from social import views

app_name = 'social'

urlpatterns = [
    path('home/', views.HomeView.as_view(), name="home"),
    path('about/', views.AboutView.as_view()),
    path('contact/', views.ContactView.as_view()),
    path('profile/edit/<int:pk>', views.MyProfileUpdateView.as_view(success_url="/social/home")),
    path('mypost/create/', views.MyPostCreate.as_view(success_url="/social/mypost")),
    path('mypost/delete/<int:pk>', views.MyPostDeleteView.as_view(success_url="/social/mypost")),
    path('mypost/', views.MyPostListView.as_view()),
    path('mypost/<int:pk>', views.MyPostDetailView.as_view()),

    path('myprofile/', views.MyProfileListView.as_view()),
    path('myprofile/<int:pk>', views.MyProfileDetailView.as_view()),

    path('myprofile/follow/<int:pk>', views.follow),
    path('myprofile/unfollow/<int:pk>', views.unfollow),

    path('mypost/like/<int:pk>', views.like),
    path('mypost/unlike/<int:pk>', views.unlike),
    #path('applicant/', include('applicant.urls', namespace='applicant')),
]

htmltopdf/models.py
from django.db import models

# Create your models here.

htmltopdf/views.py
from django.shortcuts import render,redirect
from io import BytesIO
from django.http import HttpResponse,HttpResponseRedirect
from django.template.loader import get_template
from django.views import View
from xhtml2pdf import pisa
from django.urls import reverse
from accounts.views import get_context

def render_to_pdf(template_src, context_dict={}):
	template = get_template(template_src)
	html  = template.render(context_dict)
	result = BytesIO()
	pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
	if not pdf.err:
		return HttpResponse(result.getvalue(), content_type='application/pdf')
	return None


my_dict={1:'htmltopdf/resume1.html',2:'htmltopdf/resume2.html'}
#Opens up page as PDF
class ViewPDF(View):
	def get(self, request, *args, **kwargs):
		if (template.index==1):
			pdf = render_to_pdf(my_dict[fork.design_index], {'dict':get_context(request)})
		else:
			pdf = render_to_pdf(my_dict[fork.design_index], {'dict':manual_resume.context})
		return HttpResponse(pdf, content_type='application/pdf')


#Automaticly downloads to PDF file
class DownloadPDF(View):
	def get(self, request, *args, **kwargs):
		if (template.index==1):
			pdf = render_to_pdf(my_dict[fork.design_index], {'dict':get_context(request)})
		else:
			pdf = render_to_pdf(my_dict[fork.design_index], {'dict':manual_resume.context})
		response = HttpResponse(pdf, content_type='application/pdf')
		filename = "your_resume.pdf"
		content = "attachment; filename=%s" %(filename)
		response['Content-Disposition'] = content
		return response

class fork(View):
	design_index=1
	def get(self,request,temp_index):
		setattr(fork, 'design_index',temp_index)
		return render(request,'htmltopdf/fork.html')


class template(View):
	def get(self,request,from_index):
		setattr(template,'index',from_index)
		return render(request,'htmltopdf/design_sel.html')

class manual_resume(View):
	context={}
	def get(self,request):
		setattr(template,'index',2)
		return render(request,'htmltopdf/index.html')

	def post(self,request):
		dictionary={i:request.POST.get(i) for i in request.POST}
		setattr(manual_resume, 'context',dictionary)
		return render(request,'htmltopdf/design_sel.html')
		#return HttpResponseRedirect('converter/template_sel/2')

htmltopdf/templates/htmltopdf/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {%block head_block%}
    {%endblock%}
    </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <br><br>
    <div class="container jumbotron">
      {%block body_block%}
      {%endblock%}
    </div>
  </body>
</html>

htmltopdf/templates/htmltopdf/design_sel.html
{% extends "dashboard.html" %}
{% load static %}
{% block content %}
<div class="header bg-primary pb-6">
	<div class="container-fluid">
        <div class="header-body">
            <div class="row py-4">
                <div class="col-lg-12">
                    <h6 class="h2 text-white mb-3">Resume Template</h6>
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4 col-md-12">
                    	<h1 class="mb-3 text-white">Select one of the following designs as the resume template</h1>
                    </nav>
                </div>
			</div>
		</div>
	</div>
</div>
<div class="container mt--6">
	<div class="row">
			<div class="col-md-6">
			<a href="{% url 'converter:fork' temp_index=1 %}"><img src="{% static 'ResumeA.JPG' %}" alt="Img1" height="500" width="400"></a>
		</div>
		<div class="col-md-6">
			<a href="{% url 'converter:fork' temp_index=2 %}"><img src="{% static 'ResumeB.JPG' %}" alt="Img2" height="500" width="400"></a>
		</div>
	</div>
</div>
{% endblock %}

htmltopdf/templates/htmltopdf/fork.html
{% extends "dashboard.html" %}
{% block content %}
<div class="header bg-primary pb-6">
	<div class="container-fluid">
        <div class="header-body">
            <div class="row py-4">
                <div class="col-lg-12">
                    <h6 class="h2 text-white mb-3">Resume Settings</h6>
                    <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4 col-md-12">
                    	<h1 class="mb-3 text-white">View Resume or download directly to PDF</h1>
                    </nav>
                </div>
			</div>
		</div>
	</div>
</div>
<div class="container mt--6">
	<div class="row justify-content-center">
		<a class="btn btn-info" href="{% url 'converter:pdf_view' %}" target="_blank">View Resume</a>
		<a class="btn btn-info"  href="{% url 'converter:pdf_download' %}">Download Resume</a>
		<a class="btn btn-info"  href="{% url 'index' %}">Edit Resume</a>
	</div>
</div>
<br>
{% endblock %}

htmltopdf/templates/htmltopdf/index.html
{%extends 'htmltopdf/base.html'%}

{%block head_block%}
<title>Basic Info</title>
<style media="screen">

.container{
  margin: auto;
  width: 50%;
  border: 3px solid green;
  padding: 10px;
  }
}
</style>
{%endblock%}

{%block body_block%}
<h1>Please fill the following data honestly.</h1>
<form method="post">
  {%csrf_token%}
  <table>
    <tr>
      <td><p>Headline:</p></td>
      <td><input type="text" name="headline" ></td>
    </tr>
    <tr>
      <td><p>First Name:</p></td>
      <td><input type="text" name="first_name" ></td>
    </tr>
    <tr>
      <td><p>Last Name</p></td>
      <td><input type="text" name="last_name" ></td>
    </tr>
    <tr>
      <td><p>Current Position:</p></td>
      <td><input type="text" name="current_position" ></td>
    </tr>
    <tr>
      <td><p>Education:</p></td>
      <td><input type="text" name="education" ></td>
    </tr>
    <tr>
      <td><p>Country Region</p></td>
      <td><input type="text" name="country_region" ></td>
    </tr>
    <tr>
      <td><p>Location</p></td>
      <td><input type="text" name="location"></td>
    </tr>
    <tr>
      <td><p>Industry</p></td>
      <td><input type="text" name="industry"></td>
    </tr>
    <tr>
      <td><p>Contact Information</p></td>
      <td><input type="text" name="contact_information"></td>
    </tr>
    <tr>
      <td><p>Description</p></td>
      <td><input type="text" name="description"></td>
    </tr>
    <tr>
      <td><p>School Name</p></td>
      <td><input type="text" name="school_name"></td>
    </tr>
    <tr>
      <td><p>School Degree</p></td>
      <td><input type="text" name="school_degree"></td>
    </tr>
    <tr>
      <td><p>Field of Study</p></td>
      <td><input type="text" name="field_of_study"></td>
    </tr>
    <tr>
      <td><p>Location of School</p></td>
      <td><input type="text" name="location_of_school"></td>
    </tr>
    <tr>
      <td><p>Start School</p></td>
      <td><input type="text" name="start_school"></td>
    </tr>
    <tr>
      <td><p>End School</p></td>
      <td><input type="text" name="end_school"></td>
    </tr>
    <tr>
      <td><p>Experience Title</p></td>
      <td><input type="text" name="experience_title"></td>
    </tr>
    <tr>
      <td><p>Company Name</p></td>
      <td><input type="text" name="company_name"></td>
    </tr>
    <tr>
      <td><p>Company Location</p></td>
      <td><input type="text" name="company_location"></td>
    </tr>
    <tr>
      <td><p>Start Company</p></td>
      <td><input type="text" name="start_company"></td>
    </tr>
    <tr>
      <td><p>End Company</p></td>
      <td><input type="text" name="end_company"></td>
    </tr>
    <tr>
      <td><p>Area of Expertise</p></td>
      <td><input type="text" name="area_of_expertise"></td>
    </tr>
    <tr>
      <td><p>Project Name</p></td>
      <td><input type="text" name="project_name"></td>
    </tr>
    <tr>
      <td><p>Start Project</p></td>
      <td><input type="text" name="start_project"></td>
    </tr>
    <tr>
      <td><p>End Project</p></td>
      <td><input type="text" name="end_project"></td>
    </tr>
    <tr>
      <td><p>Project Creator</p></td>
      <td><input type="text" name="project_creator"></td>
    </tr>
    <tr>
      <td><p>Assocaiated With</p></td>
      <td><input type="text" name="associated_with"></td>
    </tr>
    <tr>
      <td><p>Project URL</p></td>
      <td><input type="text" name="project_url"></td>
    </tr>
    <tr>
      <td><p>Project Description</p></td>
      <td><input type="text" name="project_description"></td>
    </tr>
    <tr>
      <td><p>Accomplishment Title</p></td>
      <td><input type="text" name="accomplisment_title"></td>
    </tr>
    <tr>
      <td><p>Accomplishment Assocaiated With</p></td>
      <td><input type="text" name="accomplisment_associated_with"></td>
    </tr>
    <tr>
      <td><p>Issuer</p></td>
      <td><input type="text" name="issuer"></td>
    </tr>
    <tr>
      <td><p>Issue Date</p></td>
      <td><input type="text" name="issue_date"></td>
    </tr>
    <tr>
      <td><p>Accomplishment Description</p></td>
      <td><input type="text" name="accomplisment_description"></td>
    </tr>
  </table>
  <input type="submit" name="" value="Submit" class="btn btn-primary">
</form>
{%endblock%}

htmltopdf/templates/htmltopdf/resume1.html
{%load myfilters%}
<head>
  <style>
    h1{font-size:400%;
    text-align:center;}
    td{font-size:250%;
    padding-right:0px;}

  </style>
  <title>Pdf</title>
</head>
<body>
  <h1>Resume</h1>
  <table>
    {% for key, value in dict.items %}
      {%if key != 'csrfmiddlewaretoken' %}
        {%if value != '[]' and value != '' and value != ' ' and value != '[""]'%}
          <tr>
            <td>{{key|correct}}</td>
            <td>{{value|forvalue}}</td>
          </tr>
        {%endif%}
      {%endif%}
    {% endfor %}
  </table>

  <hr>
    <!-- <table>
    		<tr>
          <td>Name:</td>
          <td>{{first_name}}</td></tr>
        <tr>
          <td>Address:</td>
          <td>{{addr}}</td>
        </tr>
    		<tr>
          <td>Email:</td>
    			<td>{{mail}}</td>

    		</tr>
        <tr>
          <td>DOB:</td>
          <td>{{dob}}</td>
        </tr>
        <tr>
          <td>Salary</td>
          <td>{{sal}}</td>
        </tr>
        <tr>
          <td>Experience</td>
          <td>{{exp}}</td>
        </tr>
    </table>
<hr> -->
</body>
</html>

htmltopdf/templates/htmltopdf/resume2.html
{%load myfilters%}
<head>
  <style>
      @page {
          size: a4 portrait;
          @frame header_frame {           /* Static Frame */
              -pdf-frame-content: header_content;
              left: 50pt; width: 512pt; top: 50pt; height: 40pt;
          }
          @frame content_frame {          /* Content Frame */
              left: 50pt; width: 512pt; top: 90pt; height: 632pt;
          }
          @frame footer_frame {           /* Another static Frame */
              -pdf-frame-content: footer_content;
              left: 50pt; width: 512pt; top: 772pt; height: 20pt;
          }
      }
  </style>
  </head>

  <body>
      <!-- Content for Static Frame 'header_frame' -->
      <div id="header_content">
        <h3>{{dict.first_name}} {{dict.last_name}}</h3>
      </div>

      <!-- Content for Static Frame 'footer_frame' -->
      <div id="footer_content">(c) - page <pdf:pagenumber>
          of <pdf:pagecount>
      </div>

      <table>
        {% for key, value in dict.items %}
          {%if key != 'csrfmiddlewaretoken' %}
            {%if value != '[]' and value != '' and value != ' ' and value != '[""]'%}
              <tr>
                <td>{{key|correct}}</td>
                <td>{{value|forvalue}}</td>
              </tr>
            {%endif%}
          {%endif%}
        {% endfor %}
      </table>

      <!-- HTML Content -->

      <!-- <table>
          <tr>
            <td>Address</td>
            <td>{{addr}}</td>
          </tr>
          <tr>
            <td>Email</td>
            <td>{{mail}}</td>
          </tr>
          <tr>
            <td>Date of Birth</td>
            <td>{{dob}}</td>
          </tr>
          <tr>
            <td>Salary (Lacs)</td>
            <td>{{sal}}</td>
          </tr>
          <tr>
            <td>Experience (Years)</td>
            <td>{{exp}}</td>
          </tr>
      </table> -->

      <hr>

      <hr>

  </body>
  </html>